// Mocks generated by Mockito 5.4.6 from annotations
// in super_scroll_example/test/mocks.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i6;

import 'package:mockito/mockito.dart' as _i1;
import 'package:super_scroll_example/models/business_response.dart' as _i3;
import 'package:super_scroll_example/models/community_response.dart' as _i4;
import 'package:super_scroll_example/models/user_response.dart' as _i2;
import 'package:super_scroll_example/services/business_service.dart' as _i7;
import 'package:super_scroll_example/services/community_service.dart' as _i8;
import 'package:super_scroll_example/services/user_service.dart' as _i5;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeUserResponse_0 extends _i1.SmartFake implements _i2.UserResponse {
  _FakeUserResponse_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeBusinessResponse_1 extends _i1.SmartFake
    implements _i3.BusinessResponse {
  _FakeBusinessResponse_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeCommunityResponse_2 extends _i1.SmartFake
    implements _i4.CommunityResponse {
  _FakeCommunityResponse_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [UserService].
///
/// See the documentation for Mockito's code generation for more information.
class MockUserService extends _i1.Mock implements _i5.UserService {
  MockUserService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Future<_i2.UserResponse> fetchUsers(int? page) =>
      (super.noSuchMethod(
            Invocation.method(#fetchUsers, [page]),
            returnValue: _i6.Future<_i2.UserResponse>.value(
              _FakeUserResponse_0(this, Invocation.method(#fetchUsers, [page])),
            ),
          )
          as _i6.Future<_i2.UserResponse>);
}

/// A class which mocks [BusinessService].
///
/// See the documentation for Mockito's code generation for more information.
class MockBusinessService extends _i1.Mock implements _i7.BusinessService {
  MockBusinessService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Future<_i3.BusinessResponse> fetchBusinesses(
    int? page, {
    String? search = '',
  }) =>
      (super.noSuchMethod(
            Invocation.method(#fetchBusinesses, [page], {#search: search}),
            returnValue: _i6.Future<_i3.BusinessResponse>.value(
              _FakeBusinessResponse_1(
                this,
                Invocation.method(#fetchBusinesses, [page], {#search: search}),
              ),
            ),
          )
          as _i6.Future<_i3.BusinessResponse>);
}

/// A class which mocks [CommunityService].
///
/// See the documentation for Mockito's code generation for more information.
class MockCommunityService extends _i1.Mock implements _i8.CommunityService {
  MockCommunityService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Future<_i4.CommunityResponse> fetchCommunities(int? page) =>
      (super.noSuchMethod(
            Invocation.method(#fetchCommunities, [page]),
            returnValue: _i6.Future<_i4.CommunityResponse>.value(
              _FakeCommunityResponse_2(
                this,
                Invocation.method(#fetchCommunities, [page]),
              ),
            ),
          )
          as _i6.Future<_i4.CommunityResponse>);
}
